# 5.1 PRINT

#### Print adalah perintah yang digunakan untuk mencetak kata yang ada di dalam tanda petik

#### cara penggunaan: print("...")

In [1]:
print("namaku adalah surya")

namaku adalah surya


In [2]:
print("123456")

123456


In [3]:
panjang = 30
lebar = 20
print(panjang*lebar)

600


In [6]:
prodi = "Matematika "
Fakultas = "MIPA "
Universitas = "Universitas Udayana "
print(prodi + Fakultas + Universitas)

Matematika MIPA Universitas Udayana 


# 5.2 INPUT

#### Digunakan untuk meminta informasi dari pengguna (yang menjalankan program)
#### cara penggunaan: input("...")

In [8]:
nama = input("siapakah nama anda? ")
print("Hallo " + nama + " salam kenal" )

siapakah nama anda? surya
Hallo surya salam kenal


# 5.3 TIPE DATA

#### int = bilangan bulat
#### float = bilangan desimal
#### str = huruf
#### bool = True False

#### cara mengetahui tipe data: type(variabel)

In [11]:
alas= input("panjang alas segitiga adalah ")
tinggi = input("tinggi segitiga adalah ")
luas = float(alas)* float(tinggi)
print("luas segiitiga adalah " + str(luas))

panjang alas segitiga adalah 6
tinggi segitiga adalah 5
luas segiitiga adalah 30.0


# 5.4 FORMATTED STRING

#### Untuk mempermudah penulisan nilai variabel yang ingin dicetak pada perintah print
#### penulisan:print(f"{variabel}) 

In [13]:
nama = "surya"
print(f"{nama}")

surya


# 5.5 STRINGS INDEX

#### Variabel string dapat diurutkan dengn huruf yang dimulai dengan 0.
#### uniknya di phyton huruf terakhir adalah -1, 2 dari terakhir -2 dan seterusnya
#### penggunaan: print(variabel[urutan huruf:urutan huruf])

In [15]:
nama = "I GEDE SURYA WIRAWAN"

print(nama[0:-1])
print(nama[4:8])
print(nama[6:-7])

I GEDE SURYA WIRAWA
DE S
 SURYA 


# 5.6 STRINGS METHOD

#### Beberapa methoda yang digunakan pada variabel berjenis string
#### variabel.upper()                                 : membuat huruf besar semua
#### variabel.lower()                                 : membuat hutruf kecil semua
#### variabel.find(item)                              : melihat dimana letak huruf pertama dari item (dimulai dari 0)
#### variabel replace('item sebelum , item sesuadah') : mengganti kata dalam variabel
#### print('item' in variabel)                        : mengecek apakah benar item ada di variabel (outout True or False)

In [3]:
nama= "I Gede Surya Wirawan"

nama.upper()


'I GEDE SURYA WIRAWAN'

In [4]:
nama.lower()

'i gede surya wirawan'

In [7]:
nama.find('Surya')

7

In [8]:
nama.find('Wirawan')

13

In [13]:
nama.replace('Gede' , 'Wayan')

'I Wayan Surya Wirawan'

In [17]:
print('Surya' in nama)

True


In [18]:
print('surya' in nama)
print('SURYA'in nama)

False
False


# 5.7 OPERASI MATEMATIKA DI PHYTON

#### Penjumlahan  : (x+y)
#### Pengurangan  : (x-y)
#### perkalian    : (x*y)
#### Pembagian    : (x/y)
#### pembulatan pembagian : (x//y)
#### modulo               : (x%y)
#### pemangkatan          : (x**y)
#### augmanted operator   : contoh : x+=1 yang artinya x=x+1

In [19]:
print(7+7)
print(9-3)
print(8*6)
print(6/2)
print(9//4)
print(9%5)

x=5
print(x)
x-=3
print(x)

14
6
48
3.0
2
4
5
2


# 5.8 OPERATOR PERBANDINGAN

#### Output berupa True or False

#### lebih dari  : x = a>b
#### kurang dari : x = a<b
#### lebih dari sama dengan : x = a>=b
#### kurang dari sama dengan : x= a<=b
#### sama dengan : x = a==b
#### tidak sama dengan : x = a!=b

In [22]:
x = 5>4
print(x)
y = 7>10
print(y)

True
False


In [23]:
x = 5<4
print(x)
y = 7<10
print(y)

False
True


In [25]:
x = 5>=4
print(x)
y = 10>=10
print(y)
z = 7>=10
print(z)

True
True
False


In [32]:
x = 5<=4
print(x)
y = 10<=10
print(y)
z = 7<=10
print(z)

False
True
True


In [33]:
x = 5==4
print(x)
y = 10==10
print(y)
z = 7==10
print(z)

False
True
False


In [34]:
x = 5!=4
print(x)
y = 10!=10
print(y)
z = 7!=10
print(z)

True
False
True


# 5.9 OPERATOR LOGIKA

#### Operator logika antara lain: and, or dan not. outputnya berupa True or False

In [29]:
Matkul = 7
SKS = 19
print(Matkul>3 and SKS>17)
print(Matkul<3 and SKS>17)
print(Matkul<3 and SKS<17)

True
False
False


In [30]:
Matkul = 7
SKS = 19
print(Matkul>3 or SKS>17)
print(Matkul<3 or SKS>17)
print(Matkul<3 or SKS<17)

True
True
False


In [31]:
Matkul = 7
SKS = 19
print(not(Matkul>3 and SKS>17))
print(not(Matkul<3 and SKS>17))
print(not(Matkul<3 and SKS<17))

False
True
True


# 5.10 OPERASI if & else


#### Operator if akan dijalankan bila variabel nilainya True, sedangkan jika False tidak akan dijalankan
#### Operator else dijalankan ketika variabel bernilai False
#### ketika menggunakan else kemudian diiikuti if dapat memakai elif

In [49]:
waktu = float(input("Berapa jam anda tidur sehari? "))
if waktu<=6:
    print("waktu tidur anda kurang, lebih banyakalah beristirahat")
elif waktu>6 and waktu<=9:
    print("anda sudah tidur dengan cukup")
elif waktu>9 and waktu<=24:
    print("anda terlalu banyak tidur")
else:
    print("masukkan data dengan benar")

Berapa jam anda tidur sehari? 6
waktu tidur anda kurang, lebih banyakalah beristirahat


## 
## Latihan
#### Buatlah program yang merubah tinggi badan seseorang dari cm ke inci atau sebaliknya

#### dari cm ke inci

In [1]:
tinggi = int(input("Tinggi badan anda (dalam satuan cm) adalah "))
TINGGI = float(tinggi*0.3937)
print("tinggi badan anda adalah " + str(TINGGI) + " inci")

Tinggi badan anda (dalam satuan cm) adalah 155
tinggi badan anda adalah 61.0235 inci


#### dari inci ke cm

In [2]:
tinggi = float(input("Tinggi badan anda (dalam satuan inci) adalah "))
TINGGI = float(tinggi*2.54)
print("tinggi badan anda adalah " + str(TINGGI) + " cm")

Tinggi badan anda (dalam satuan inci) adalah 50
tinggi badan anda adalah 127.0 cm


# 5.11 WHILE LOOP
#### While loop selalu dieksekusi ketika variabel bernilai True dan berhenti ketika False

In [1]:
a=0
while a<10:
    print("angka " + str(a) + " lebih kecil dari 10")
    a+=1

angka 0 lebih kecil dari 10
angka 1 lebih kecil dari 10
angka 2 lebih kecil dari 10
angka 3 lebih kecil dari 10
angka 4 lebih kecil dari 10
angka 5 lebih kecil dari 10
angka 6 lebih kecil dari 10
angka 7 lebih kecil dari 10
angka 8 lebih kecil dari 10
angka 9 lebih kecil dari 10


In [2]:
a=1
while a<10:
    print(a*"*")
    a+=1

*
**
***
****
*****
******
*******
********
*********


# 5.12 LIST DI PHYTON
#### Mempresentasikan objek dilalam phyton baik string maupun berupa angka

In [3]:
pemain = ['Messi' , 'Iniesta' , 'Puyol' , 'Xavi']
print(pemain)

['Messi', 'Iniesta', 'Puyol', 'Xavi']


In [4]:
print(pemain[0])
print(pemain[1])
print(pemain[2])
print(pemain[3])
print(pemain[-2])

Messi
Iniesta
Puyol
Xavi
Puyol


In [5]:
print(pemain[0:5])
print(pemain[1:-1])

['Messi', 'Iniesta', 'Puyol', 'Xavi']
['Iniesta', 'Puyol']


In [6]:
pemain[2] = 'Busquets'
print(pemain)

['Messi', 'Iniesta', 'Busquets', 'Xavi']


# 5.13 METODA LIST
#### Memanipulasi isi list seperti menambahkan atau menghilangkan isinya
#### variabel.append('item') untuk menambahkan isi
#### variabel.insert(pos,'item') untuk menambahkan di posisi yang kita inginkan
#### variabel.remove('item) untuk menghilangkan isi
#### len(variabel) untuk mengecek jumlah item

In [7]:
pemain.append('Neymar')
print(pemain)

['Messi', 'Iniesta', 'Busquets', 'Xavi', 'Neymar']


In [8]:
pemain.insert(4,'Suarez')
print(pemain)

['Messi', 'Iniesta', 'Busquets', 'Xavi', 'Suarez', 'Neymar']


In [9]:
pemain.remove('Neymar')
print(pemain)

['Messi', 'Iniesta', 'Busquets', 'Xavi', 'Suarez']


In [10]:
print(len(pemain))

5


# 5.14 FOR LOOP
#### Digunakan untuk memanggil semua isi list

In [11]:
for Pemain in pemain:
    print(Pemain)

Messi
Iniesta
Busquets
Xavi
Suarez


# 5.15 FUNGSI RANGE
#### membangkitkan bilangan berurutan atau berpola. dalam penggunaannya dikombinasikan dengan for

In [14]:
angka = range(10)
print(angka)

range(0, 10)


In [15]:
for isi in angka:
    print(isi)

0
1
2
3
4
5
6
7
8
9


In [20]:
for isi in range(5,10):
    print(isi)

5
6
7
8
9


In [23]:
for isi in range(0,10,3):
    print(isi)

0
3
6
9


### Latihan
#### 1. Buatlah program umtuk menncari nilai terbesar didalam suatu list

In [39]:
data = [4,10,3,8]
maks = data[0]
for x in range(len(data)):
    if data[x] > maks:
        maks = data[x]
print(maks)

10


#### 2. Buatlah program untuk membuat anggota list menjadi unik dengan kata lain tidak ada anggota list  yang kembar

In [44]:
data = [0,1,3,3,4,3,4,5,7,3,5,4]
data_unik = []
for x in data:
    if x not in data_unik:
        data_unik.append(x)
print(data_unik)

[0, 1, 3, 4, 5, 7]


# 5.16 LIST 2 DIMENSI
#### Menempatkan list dalam list

In [2]:
matrik = [1,2,3],[4,5,6],[7,8,9]
print(matrik)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [7]:
matrik[2]

[7, 8, 9]

In [8]:
matrik[1][0]

4

In [9]:
matrik[2][1]=10
print(matrik)

([1, 2, 3], [4, 5, 6], [7, 10, 9])


In [11]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[7, 10, 9]
7
10
9


# 5.17 TUPLES
#### Mirip seperti list namun tidak dapat diubah isinya

In [5]:
angka = (2,4,6,8,10,12)

In [3]:
print(angka[4])

10


In [4]:
print(angka[3:5])

(8, 10)


In [5]:
for isi in angka:
    print(isi)

2
4
6
8
10
12


In [6]:
angka 0 = 4
angka.append(14)
angka.remove(4)

SyntaxError: invalid syntax (Temp/ipykernel_12876/1163626827.py, line 1)

#### Seperti yang sudah dijelaskan sebelumnya tupples tidak bisa diubah isi datanya 
#### terdapat fungsi count dan index. count berfungsi untuk menghitung ada berapa jumlah data yang ingin diketahui. index untuk mengetahui berada di urutan berapa data tersebut berada (dimulai dari 0)

In [6]:
angka.count(2)

1

In [7]:
angka.index(4)

1

# 5.18 DICTIONARIES
#### Dictionaries digunakan jika data terikat satu sama lain

In [8]:
data_pemain = {
    'Nama' : 'Lionel Messi',
    'negara' : 'Argentina',
    'posisi' : 'Forward'
}

print(data_pemain['Nama'])

Lionel Messi


In [9]:
print(data_pemain['negara'])

Argentina


In [10]:
print(data_pemain['posisi'])

Forward


### Latihan
#### Buatlah program untuk merubah nomor yang tadinya berupa angka menjadi sebutan bilangan tersebut.  Misalnya angka 0812 akan menjadi nol delapan satu dua

In [11]:
angka ={
    '0' : 'nol ',
    '1' : 'satu ',
    '2' : 'dua ',
    '3' : 'tiga ',
    '4' : 'empat ',
    '5' : 'lima ',
    '6' : 'enam ',
    '7' : 'tujuh ',
    '8' : 'delapan ',
    '9' : 'sembilan '
}

In [13]:
nomor_hp = input("masukkan nomor HP anda ")
nomor_angka = ""
for isi in nomor_hp:
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

masukkan nomor HP anda 09876543212235456534565565666666
nol sembilan delapan tujuh enam lima empat tiga dua satu dua dua tiga lima empat lima enam lima tiga empat lima enam lima lima enam lima enam enam enam enam enam enam 


# 5.19 FUNGSI DALAM PHYTON
#### 

In [3]:
def full name(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")
first_name = input("Nama depan anda adalah? ")
last_name = input ("Nama belakang anda adalah? ")
full_name(first_name,last_name)

SyntaxError: invalid syntax (Temp/ipykernel_11892/3236554953.py, line 1)

# 5.20 NUMPY

## 5.20.1 Perintah dasar numpy

In [4]:
import numpy as np

In [29]:
a = np.zeros((10,10))
print(a)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
a[1:-1,1:-1]=1
a[2:-2,2:-2]=0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
a[3:-3,3:-3]=2
a[4:-4,4:-4]=0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


IndentationError: unexpected indent (Temp/ipykernel_11892/2950042008.py, line 2)